FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/

COPY models/ /usr/share/nginx/html/models/
COPY textures/ /usr/share/nginx/html/textures/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80