services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: terrain_backend
    restart: always
    env_file:
    - .env
    environment:
      - DB_PATH=/app/data/users.db
    volumes:
      - db_data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: terrain_frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

volumes:
  db_data: